server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/soirees_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: false


#Eureka
eureka:
  instance:
    health-check-url-path: /soirees/actuator/health
    statusPageUrlPath: /soirees/actuator/info
