server:
#  servlet:
#    context-path: /users
  port: 8084

feign:
  hystrix:
    enabled: true

#Oauth2
security:
  oauth2:
    client:
      clientId: ms_users
      clientSecret: 123
      accessTokenUri: http://ms_authentification:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/users_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      write-dates-as-timestamps: false


#Eureka
eureka:
  instance:
    health-check-url-path: /users/actuator/health
    statusPageUrlPath: /users/actuator/info
